Holamundo:
	g++ -Wall HolaMundo.cpp -o HolaMundo.o

Holaname:
	g++ -Wall HolaName.cpp -o HolaName.o

Clear:
	rm *.o

All:
	g++ -Wall HolaMundo.cpp -o HolaMundo.o
	g++ -Wall HolaName.cpp -o HolaName.o

